INSERT INTO PROVIDER_INFO(NAME, STATE, ADDRESS) VALUES('Fornecedor-GO', 'GO', 'Endereço fornecedor de Goias');
INSERT INTO PRODUCT(DESCRIPTION, STATE, NAME, PRICE) VALUES('rosas', 'DF', 'rosas', 1.99);
INSERT INTO PRODUCT(DESCRIPTION, STATE, NAME, PRICE) VALUES('orquidea', 'DF', 'orquidea', 25);
INSERT INTO PRODUCT(DESCRIPTION, STATE, NAME, PRICE) VALUES('girassol', 'DF', 'girassol', 5);